/// Flutter icons TWIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TWIcons
///      fonts:
///       - asset: fonts/TWIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class TWIcons {
  TWIcons._();

  static const _kFontFam = 'TWIcons';

  static const IconData backarrow = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData zoomicon = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData doc_text = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData layout = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData grid = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData note = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData count_doc = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData pointer = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData help = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData down = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData layer = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData ruler = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData fullscreen = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData downarrow = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData setting = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData map = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData account = IconData(0xe812, fontFamily: _kFontFam);
}
